# Generated by Django 5.2.9 on 2026-02-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_complaintaction_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='status',
            field=models.CharField(default='active', max_length=40),
        ),
    ]
