# Generated by Django 5.2.9 on 2026-02-26 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.complaint'),
        ),
    ]
